name: first-action
on: 
  workflow_dispatch:
  pull_request:
    types: [labeled]
jobs:
  pre-requisite-Job:
    runs-on: ubuntu-latest
    outputs:
      env_target: ${{ steps.setenv.outputs.env_target }}
    steps:
      - name: Detect label and set environment variable
        id: setenv
        run: |
          echo "Checking for 'production' label..."
          # Check if the pull request has a label named 'production'
          # If it does, set the environment variable to 'production'
          # Otherwise, set it to 'devtest'
          echo "Labels: ${{ github.event.pull_request.labels.*.name }}"
          if [[ "${{ github.event.pull_request.labels.*.name }}" == *production* ]]; then
            echo "env_target=production" >> $GITHUB_OUTPUT
          else
            echo "env_target=devtest" >> $GITHUB_OUTPUT
          fi
  first-job:
    runs-on: ubuntu-latest
    needs: pre-requisite-Job
    env:
      ENV_TARGET: ${{ needs.pre-requisite-Job.outputs.env_target }}
    steps:
      - name: Show ENV_TARGET
        run: echo "ENV_TARGET is $ENV_TARGET"
      - name: first-step Print Greeting
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Done Bye"
  second-job:
    runs-on: ubuntu-latest
    needs: [pre-requisite-Job, first-job]
    env:
      ENV_TARGET: ${{ needs.pre-requisite-Job.outputs.env_target }}
    environment: ${{ needs.pre-requisite-Job.outputs.env_target }}
    steps:
      - name: Show ENV_TARGET
        run: echo "ENV_TARGET is $ENV_TARGET"
      - name: second-job
        run: echo "output from 2nd Job"

